/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;

/**
 *
 * @author Dewberry
 */
public class GameFrame extends javax.swing.JFrame {
    StartFrame startFrame;
    
    Animation animCharacter1;
    
    ImageIcon icon_shutdown, icon_shutdown_h, icon_shutdown_f, icon_shutdown_h_f;
    ImageIcon icon_start, icon_start_h, icon_start_f, icon_start_h_f;
    ImageIcon startBg, startBg_f;
    
    private int dragXPos, dragYPos;
    
    private BackgroundMusic bgMusic;
    private String bgmClick = "Blop.wav";
    /**
     * Creates new form GameFrame
     */
    public GameFrame(){
        
        startFrame = new StartFrame();
        //load animations and variables
        animCharacter1 = new Animation(127, "animChar1", "sprite_");
        
        
        initComponents();
        
        bgMusic = new BackgroundMusic("track3.wav");
        
        
        loadGame();
        
        bgMusic.play();
    }
    
    public void update(){
        animCharacter1.animate(testIcon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblHighscore = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        testIcon = new javax.swing.JLabel();
        dragPanel = new javax.swing.JPanel();
        btn_start = new javax.swing.JLabel();
        GameFrame_Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1025, 576));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1025, 576));
        setResizable(false);
        setSize(new java.awt.Dimension(1025, 576));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel2.setMinimumSize(new java.awt.Dimension(1025, 576));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHighscore.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblHighscore.setForeground(new java.awt.Color(204, 204, 204));
        lblHighscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHighscore.setText("High Score: 0");
        jPanel2.add(lblHighscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 220, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_shutdown_2.png"))); // NOI18N
        btn_exit.setToolTipText("Exit");
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        testIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/animChar1/sprite_0001.png"))); // NOI18N
        jPanel2.add(testIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -30, 720, 580));

        dragPanel.setOpaque(false);

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 50));

        btn_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_start_2.png"))); // NOI18N
        btn_start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 50));

        GameFrame_Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_2.png"))); // NOI18N
        GameFrame_Bg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        GameFrame_Bg.setMaximumSize(new java.awt.Dimension(1366, 768));
        GameFrame_Bg.setMinimumSize(new java.awt.Dimension(1366, 768));
        GameFrame_Bg.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.add(GameFrame_Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if (StartFrame.highscore != 0){
            
            lblHighscore.setVisible(true);
            lblHighscore.setText("High Score: " + StartFrame.highscore);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameFrame_Bg;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_start;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHighscore;
    private javax.swing.JLabel testIcon;
    // End of variables declaration//GEN-END:variables

    private void loadGame() {
        loadImages();
        lblHighscore.setVisible(false);
        
        dragXPos = -1; //for drag panel
        dragYPos = -1; //for drag panel
        
        
        btn_start.addMouseListener(new MouseAdapter(){
            public void mouseEntered(MouseEvent e) {
                
                new BackgroundMusic(bgmClick).play();
                btn_start.setIcon(icon_start_h);
            }
            public void mouseExited(MouseEvent e) {
                btn_start.setIcon(icon_start);
            }
            public void mouseReleased(MouseEvent e) {
                new BackgroundMusic("transition.wav").play();
                bgMusic.stop();
                startGame();
                
            }});
        
        btn_exit.addMouseListener(new MouseAdapter(){
            public void mouseEntered(MouseEvent e) {
                new BackgroundMusic(bgmClick).play();
                btn_exit.setIcon(icon_shutdown_h);
            }
            public void mouseExited(MouseEvent e) {
                btn_exit.setIcon(icon_shutdown);
            }
            public void mouseReleased(MouseEvent e) {
                System.exit(0);
            }});
        
        
        
        //---DRAG PANEL---
        dragPanel.addMouseMotionListener(new MouseMotionAdapter(){
            public void mouseDragged(MouseEvent e) {
                if (dragXPos == -1) {
                    dragXPos = e.getX();
                }
                if (dragYPos == -1) {
                    dragYPos = e.getY();
                }
                setLocation(e.getXOnScreen() - dragXPos, e.getYOnScreen() - dragYPos);
            }});
        
        dragPanel.addMouseListener(new MouseAdapter(){
            //Clears the mouse drag position
            public void mouseReleased(MouseEvent e) {
                dragXPos = -1;
                dragYPos = -1;
            }
        });
    }
    //START GAME//
    private void startGame() {
        startFrame.setVisible(true);
        this.dispose();
    }

    //loads all images
    private void loadImages() {
        
        icon_start = loadImage("icon_start", "", "_2");
        icon_start_h = loadImage("icon_start", "_h", "_2");
        
        
        icon_shutdown = loadImage("icon_shutdown", "", "_2");
        icon_shutdown_h = loadImage("icon_shutdown", "_h", "_2");
        
        startBg = loadImage("startBg", "", "_2");
    }
    
    private ImageIcon loadImage(String imageName, String type, String size){
        ImageIcon image = new ImageIcon(getClass().getResource("/images/" + imageName + type + size + ".png"));
        return image;
    }
    //------------------end of game loader-------------//
    
    
}
